 
 

export type ItemType = typeof Songsitems[0];// Define a type for the items

   

    export const Songsitems = [
        {
          "type": "track",
          "id": 1146061294,
          "permalink": "https://soundcloud.com/edsheeran/ed-sheeran-tides",
          "createdAt": "2021-10-22T11:20:28Z",
          "lastModified": "2023-10-25T23:58:43Z",
          "title": "Ed Sheeran - Tides",
          "caption": null,
          "description": null,
          "goPlus": false,
          "durationMs": 195788,
          "durationText": "03:15",
          "artworkUrl": "https://i1.sndcdn.com/artworks-3W7w2avzTtmZ-0-original.jpg",
          "releaseDate": "2021-10-29T00:00:00Z",
          "genre": "Pop",
          "labelName": "Atlantic Records UK",
          "license": "all-rights-reserved",
          "purchaseTitle": null,
          "purchaseUrl": null,
          "commentable": true,
          "commentCount": 32,
          "likeCount": 1535,
          "playCount": 107741,
          "repostCount": 129,
          "waveformUrl": "https://wave.sndcdn.com/VJMoVBDNqxRI_m.json",
          "stationPermalink": "https://soundcloud.com/discover/sets/track-stations:1146061294",
          "visuals": [],
          "publisher": {
            "albumTitle": "=",
            "artist": "Ed Sheeran",
            "writerComposer": "Ed Sheeran, Foy Vance, Johnny McDaid",
            "upcOrEan": "190296491412",
            "isrc": "GBAHS2100670",
            "pLine": "℗ An Asylum Records UK release, a division of Atlantic Records UK, ℗ 2021 Warner Music UK Limited",
            "cLine": "© An Asylum Records UK release, a division of Atlantic Records UK, © 2021 Warner Music UK Limited"
          },
          "tags": [],
          "user": {
            "type": "user",
            "id": 3685019,
            "permalink": "https://soundcloud.com/edsheeran",
            "lastModified": "2023-09-29T05:02:30Z",
            "name": "Ed Sheeran",
            "avatarUrl": "https://i1.sndcdn.com/avatars-p1k8SAWgqCaOVZMa-8Z8LOQ-original.jpg",
            "followerCount": 2470753,
            "city": "",
            "countryCode": null,
            "verified": true,
            "pro": false,
            "proUnlimited": false,
            "stationPermalink": "https://soundcloud.com/discover/sets/artist-stations:3685019"
          }
        },
        {
          "type": "track",
          "id": 1118084470,
          "permalink": "https://soundcloud.com/edsheeran/ed-sheeran-shivers",
          "createdAt": "2021-09-03T10:16:46Z",
          "lastModified": "2023-10-25T23:58:55Z",
          "title": "Ed Sheeran - Shivers",
          "caption": null,
          "description": null,
          "goPlus": false,
          "durationMs": 207882,
          "durationText": "03:27",
          "artworkUrl": "https://i1.sndcdn.com/artworks-1CZouzfcjxU8-0-original.jpg",
          "releaseDate": "2021-09-10T00:00:00Z",
          "genre": "Pop",
          "labelName": "Atlantic Records UK",
          "license": "all-rights-reserved",
          "purchaseTitle": null,
          "purchaseUrl": null,
          "commentable": true,
          "commentCount": 2517,
          "likeCount": 125221,
          "playCount": 9357983,
          "repostCount": 6830,
          "waveformUrl": "https://wave.sndcdn.com/tSxvlOUfYhGd_m.json",
          "stationPermalink": "https://soundcloud.com/discover/sets/track-stations:1118084470",
          "visuals": [],
          "publisher": {
            "albumTitle": "Shivers",
            "artist": "Ed Sheeran",
            "writerComposer": "Ed Sheeran, Johnny McDaid, Kal Lavelle, Steve Mac",
            "upcOrEan": "190296468940",
            "isrc": "GBAHS2100671",
            "pLine": "℗ An Asylum Records UK release, a division of Atlantic Records UK, ℗ 2021 Warner Music UK Limited",
            "cLine": "© An Asylum Records UK release, a division of Atlantic Records UK, © 2021 Warner Music UK Limited"
          },
          "tags": [],
          "user": {
            "type": "user",
            "id": 3685019,
            "permalink": "https://soundcloud.com/edsheeran",
            "lastModified": "2023-09-29T05:02:30Z",
            "name": "Ed Sheeran",
            "avatarUrl": "https://i1.sndcdn.com/avatars-p1k8SAWgqCaOVZMa-8Z8LOQ-original.jpg",
            "followerCount": 2470753,
            "city": "",
            "countryCode": null,
            "verified": true,
            "pro": false,
            "proUnlimited": false,
            "stationPermalink": "https://soundcloud.com/discover/sets/artist-stations:3685019"
          }
        },
        {
          "type": "track",
          "id": 1146061291,
          "permalink": "https://soundcloud.com/edsheeran/ed-sheeran-first-times",
          "createdAt": "2021-10-22T11:20:28Z",
          "lastModified": "2023-10-25T23:59:08Z",
          "title": "Ed Sheeran - First Times",
          "caption": null,
          "description": null,
          "goPlus": false,
          "durationMs": 185887,
          "durationText": "03:05",
          "artworkUrl": "https://i1.sndcdn.com/artworks-41EtNotYaeyO-0-original.jpg",
          "releaseDate": "2021-10-29T00:00:00Z",
          "genre": "Pop",
          "labelName": "Atlantic Records UK",
          "license": "all-rights-reserved",
          "purchaseTitle": null,
          "purchaseUrl": null,
          "commentable": true,
          "commentCount": 30,
          "likeCount": 1661,
          "playCount": 113335,
          "repostCount": 47,
          "waveformUrl": "https://wave.sndcdn.com/YeD6ZS5OYOyT_m.json",
          "stationPermalink": "https://soundcloud.com/discover/sets/track-stations:1146061291",
          "visuals": [],
          "publisher": {
            "albumTitle": "=",
            "artist": "Ed Sheeran",
            "writerComposer": "David Hodges, Ed Sheeran, Fred Gibson",
            "upcOrEan": "190296491412",
            "isrc": "GBAHS2100672",
            "pLine": "℗ An Asylum Records UK release, a division of Atlantic Records UK, ℗ 2021 Warner Music UK Limited",
            "cLine": "© An Asylum Records UK release, a division of Atlantic Records UK, © 2021 Warner Music UK Limited"
          },
          "tags": [],
          "user": {
            "type": "user",
            "id": 3685019,
            "permalink": "https://soundcloud.com/edsheeran",
            "lastModified": "2023-09-29T05:02:30Z",
            "name": "Ed Sheeran",
            "avatarUrl": "https://i1.sndcdn.com/avatars-p1k8SAWgqCaOVZMa-8Z8LOQ-original.jpg",
            "followerCount": 2470753,
            "city": "",
            "countryCode": null,
            "verified": true,
            "pro": false,
            "proUnlimited": false,
            "stationPermalink": "https://soundcloud.com/discover/sets/artist-stations:3685019"
          }
        },
        {
          "type": "track",
          "id": 1071204931,
          "permalink": "https://soundcloud.com/edsheeran/ed-sheeran-bad-habits",
          "createdAt": "2021-06-18T11:16:46Z",
          "lastModified": "2023-10-25T23:57:24Z",
          "title": "Ed Sheeran - Bad Habits",
          "caption": null,
          "description": null,
          "goPlus": false,
          "durationMs": 230792,
          "durationText": "03:50",
          "artworkUrl": "https://i1.sndcdn.com/artworks-kyfYPWUHcbGK-0-original.jpg",
          "releaseDate": "2021-06-25T00:00:00Z",
          "genre": "Pop",
          "labelName": "Atlantic Records UK",
          "license": "all-rights-reserved",
          "purchaseTitle": null,
          "purchaseUrl": null,
          "commentable": true,
          "commentCount": 6386,
          "likeCount": 243356,
          "playCount": 16219973,
          "repostCount": 8998,
          "waveformUrl": "https://wave.sndcdn.com/IMNTkQJBuOkz_m.json",
          "stationPermalink": "https://soundcloud.com/discover/sets/track-stations:1071204931",
          "visuals": [],
          "publisher": {
            "albumTitle": "Bad Habits",
            "artist": "Ed Sheeran",
            "writerComposer": "Ed Sheeran, Fred Gibson, Johnny McDaid",
            "upcOrEan": "190296614316",
            "isrc": "GBAHS2100318",
            "pLine": "℗ An Asylum Records UK release, a division of Atlantic Records UK, ℗ 2021 Warner Music UK Limited",
            "cLine": "© An Asylum Records UK release, a division of Atlantic Records UK, © 2021 Warner Music UK Limited"
          },
          "tags": [],
          "user": {
            "type": "user",
            "id": 3685019,
            "permalink": "https://soundcloud.com/edsheeran",
            "lastModified": "2023-09-29T05:02:30Z",
            "name": "Ed Sheeran",
            "avatarUrl": "https://i1.sndcdn.com/avatars-p1k8SAWgqCaOVZMa-8Z8LOQ-original.jpg",
            "followerCount": 2470753,
            "city": "",
            "countryCode": null,
            "verified": true,
            "pro": false,
            "proUnlimited": false,
            "stationPermalink": "https://soundcloud.com/discover/sets/artist-stations:3685019"
          }
        },
        {
          "type": "track",
          "id": 1146060724,
          "permalink": "https://soundcloud.com/edsheeran/ed-sheeran-overpass-graffiti",
          "createdAt": "2021-10-22T11:19:44Z",
          "lastModified": "2023-10-25T23:57:59Z",
          "title": "Ed Sheeran - Overpass Graffiti",
          "caption": null,
          "description": null,
          "goPlus": false,
          "durationMs": 236957,
          "durationText": "03:56",
          "artworkUrl": "https://i1.sndcdn.com/artworks-YLOY1kEqh4SD-0-original.jpg",
          "releaseDate": "2021-10-29T00:00:00Z",
          "genre": "Pop",
          "labelName": "Atlantic Records UK",
          "license": "all-rights-reserved",
          "purchaseTitle": null,
          "purchaseUrl": null,
          "commentable": true,
          "commentCount": 1589,
          "likeCount": 75073,
          "playCount": 2396686,
          "repostCount": 6099,
          "waveformUrl": "https://wave.sndcdn.com/YMNp3cz93GbV_m.json",
          "stationPermalink": "https://soundcloud.com/discover/sets/track-stations:1146060724",
          "visuals": [],
          "publisher": {
            "albumTitle": "=",
            "artist": "Ed Sheeran",
            "writerComposer": "Ed Sheeran, Fred Gibson, Johnny McDaid",
            "upcOrEan": "190296491412",
            "isrc": "GBAHS2100673",
            "pLine": "℗ An Asylum Records UK release, a division of Atlantic Records UK, ℗ 2021 Warner Music UK Limited",
            "cLine": "© An Asylum Records UK release, a division of Atlantic Records UK, © 2021 Warner Music UK Limited"
          },
          "tags": [],
          "user": {
            "type": "user",
            "id": 3685019,
            "permalink": "https://soundcloud.com/edsheeran",
            "lastModified": "2023-09-29T05:02:30Z",
            "name": "Ed Sheeran",
            "avatarUrl": "https://i1.sndcdn.com/avatars-p1k8SAWgqCaOVZMa-8Z8LOQ-original.jpg",
            "followerCount": 2470753,
            "city": "",
            "countryCode": null,
            "verified": true,
            "pro": false,
            "proUnlimited": false,
            "stationPermalink": "https://soundcloud.com/discover/sets/artist-stations:3685019"
          }
        },
        {
          "type": "track",
          "id": 1146058468,
          "permalink": "https://soundcloud.com/edsheeran/ed-sheeran-the-joker-and-the",
          "createdAt": "2021-10-22T11:16:43Z",
          "lastModified": "2023-10-25T23:57:40Z",
          "title": "Ed Sheeran - The Joker And The Queen",
          "caption": null,
          "description": null,
          "goPlus": false,
          "durationMs": 185626,
          "durationText": "03:05",
          "artworkUrl": "https://i1.sndcdn.com/artworks-A1BlNK1wcUyH-0-original.jpg",
          "releaseDate": "2021-10-29T00:00:00Z",
          "genre": "Pop",
          "labelName": "Atlantic Records UK",
          "license": "all-rights-reserved",
          "purchaseTitle": null,
          "purchaseUrl": null,
          "commentable": true,
          "commentCount": 49,
          "likeCount": 1360,
          "playCount": 94268,
          "repostCount": 41,
          "waveformUrl": "https://wave.sndcdn.com/qPNJjjJJytfT_m.json",
          "stationPermalink": "https://soundcloud.com/discover/sets/track-stations:1146058468",
          "visuals": [],
          "publisher": {
            "albumTitle": "=",
            "artist": "Ed Sheeran",
            "writerComposer": "Ed Sheeran, Fred Gibson, Johnny McDaid, Sam Roman",
            "upcOrEan": "190296491412",
            "isrc": "GBAHS2100674",
            "pLine": "℗ An Asylum Records UK release, a division of Atlantic Records UK, ℗ 2021 Warner Music UK Limited",
            "cLine": "© An Asylum Records UK release, a division of Atlantic Records UK, © 2021 Warner Music UK Limited"
          },
          "tags": [],
          "user": {
            "type": "user",
            "id": 3685019,
            "permalink": "https://soundcloud.com/edsheeran",
            "lastModified": "2023-09-29T05:02:30Z",
            "name": "Ed Sheeran",
            "avatarUrl": "https://i1.sndcdn.com/avatars-p1k8SAWgqCaOVZMa-8Z8LOQ-original.jpg",
            "followerCount": 2470753,
            "city": "",
            "countryCode": null,
            "verified": true,
            "pro": false,
            "proUnlimited": false,
            "stationPermalink": "https://soundcloud.com/discover/sets/artist-stations:3685019"
          }
        },
        {
          "type": "track",
          "id": 1146062995,
          "permalink": "https://soundcloud.com/edsheeran/ed-sheeran-leave-your-life",
          "createdAt": "2021-10-22T11:22:32Z",
          "lastModified": "2023-10-25T23:59:30Z",
          "title": "Ed Sheeran - Leave Your Life",
          "caption": null,
          "description": null,
          "goPlus": false,
          "durationMs": 223896,
          "durationText": "03:43",
          "artworkUrl": "https://i1.sndcdn.com/artworks-yAKYvVsuL4RH-0-original.jpg",
          "releaseDate": "2021-10-29T00:00:00Z",
          "genre": "Pop",
          "labelName": "Atlantic Records UK",
          "license": "all-rights-reserved",
          "purchaseTitle": null,
          "purchaseUrl": null,
          "commentable": true,
          "commentCount": 16,
          "likeCount": 1084,
          "playCount": 77468,
          "repostCount": 114,
          "waveformUrl": "https://wave.sndcdn.com/0gkKH7biD3Mr_m.json",
          "stationPermalink": "https://soundcloud.com/discover/sets/track-stations:1146062995",
          "visuals": [],
          "publisher": {
            "albumTitle": "=",
            "artist": "Ed Sheeran",
            "writerComposer": "Ed Sheeran",
            "upcOrEan": "190296491412",
            "isrc": "GBAHS2100675",
            "pLine": "℗ An Asylum Records UK release, a division of Atlantic Records UK, ℗ 2021 Warner Music UK Limited",
            "cLine": "© An Asylum Records UK release, a division of Atlantic Records UK, © 2021 Warner Music UK Limited"
          },
          "tags": [],
          "user": {
            "type": "user",
            "id": 3685019,
            "permalink": "https://soundcloud.com/edsheeran",
            "lastModified": "2023-09-29T05:02:30Z",
            "name": "Ed Sheeran",
            "avatarUrl": "https://i1.sndcdn.com/avatars-p1k8SAWgqCaOVZMa-8Z8LOQ-original.jpg",
            "followerCount": 2470753,
            "city": "",
            "countryCode": null,
            "verified": true,
            "pro": false,
            "proUnlimited": false,
            "stationPermalink": "https://soundcloud.com/discover/sets/artist-stations:3685019"
          }
        },
        {
          "type": "track",
          "id": 1146058312,
          "permalink": "https://soundcloud.com/edsheeran/ed-sheeran-collide",
          "createdAt": "2021-10-22T11:16:30Z",
          "lastModified": "2023-10-25T23:58:32Z",
          "title": "Ed Sheeran - Collide",
          "caption": null,
          "description": null,
          "goPlus": false,
          "durationMs": 210260,
          "durationText": "03:30",
          "artworkUrl": "https://i1.sndcdn.com/artworks-2Xe2uhTgCC68-0-original.jpg",
          "releaseDate": "2021-10-29T00:00:00Z",
          "genre": "Pop",
          "labelName": "Atlantic Records UK",
          "license": "all-rights-reserved",
          "purchaseTitle": null,
          "purchaseUrl": null,
          "commentable": true,
          "commentCount": 12,
          "likeCount": 1070,
          "playCount": 83052,
          "repostCount": 27,
          "waveformUrl": "https://wave.sndcdn.com/nBbH8wPEe33L_m.json",
          "stationPermalink": "https://soundcloud.com/discover/sets/track-stations:1146058312",
          "visuals": [],
          "publisher": {
            "albumTitle": "=",
            "artist": "Ed Sheeran",
            "writerComposer": "Ben Kweller, Ed Sheeran, Fred Gibson, Johnny McDaid",
            "upcOrEan": "190296491412",
            "isrc": "GBAHS2100676",
            "pLine": "℗ An Asylum Records UK release, a division of Atlantic Records UK, ℗ 2021 Warner Music UK Limited",
            "cLine": "© An Asylum Records UK release, a division of Atlantic Records UK, © 2021 Warner Music UK Limited"
          },
          "tags": [],
          "user": {
            "type": "user",
            "id": 3685019,
            "permalink": "https://soundcloud.com/edsheeran",
            "lastModified": "2023-09-29T05:02:30Z",
            "name": "Ed Sheeran",
            "avatarUrl": "https://i1.sndcdn.com/avatars-p1k8SAWgqCaOVZMa-8Z8LOQ-original.jpg",
            "followerCount": 2470753,
            "city": "",
            "countryCode": null,
            "verified": true,
            "pro": false,
            "proUnlimited": false,
            "stationPermalink": "https://soundcloud.com/discover/sets/artist-stations:3685019"
          }
        },
        {
          "type": "track",
          "id": 1146060469,
          "permalink": "https://soundcloud.com/edsheeran/ed-sheeran-2step",
          "createdAt": "2021-10-22T11:19:23Z",
          "lastModified": "2023-10-25T23:58:20Z",
          "title": "Ed Sheeran - 2step",
          "caption": null,
          "description": null,
          "goPlus": false,
          "durationMs": 153678,
          "durationText": "02:33",
          "artworkUrl": "https://i1.sndcdn.com/artworks-OvH3K75EeCdu-0-original.jpg",
          "releaseDate": "2021-10-29T00:00:00Z",
          "genre": "Pop",
          "labelName": "Atlantic Records UK",
          "license": "all-rights-reserved",
          "purchaseTitle": null,
          "purchaseUrl": null,
          "commentable": true,
          "commentCount": 92,
          "likeCount": 6069,
          "playCount": 441037,
          "repostCount": 151,
          "waveformUrl": "https://wave.sndcdn.com/85li1fl19rTT_m.json",
          "stationPermalink": "https://soundcloud.com/discover/sets/track-stations:1146060469",
          "visuals": [],
          "publisher": {
            "albumTitle": "=",
            "artist": "Ed Sheeran",
            "writerComposer": "Andrew Wotman, David Hodges, Ed Sheeran, Louis Bell",
            "upcOrEan": "190296491412",
            "isrc": "GBAHS2100677",
            "pLine": "℗ An Asylum Records UK release, a division of Atlantic Records UK, ℗ 2021 Warner Music UK Limited",
            "cLine": "© An Asylum Records UK release, a division of Atlantic Records UK, © 2021 Warner Music UK Limited"
          },
          "tags": [],
          "user": {
            "type": "user",
            "id": 3685019,
            "permalink": "https://soundcloud.com/edsheeran",
            "lastModified": "2023-09-29T05:02:30Z",
            "name": "Ed Sheeran",
            "avatarUrl": "https://i1.sndcdn.com/avatars-p1k8SAWgqCaOVZMa-8Z8LOQ-original.jpg",
            "followerCount": 2470753,
            "city": "",
            "countryCode": null,
            "verified": true,
            "pro": false,
            "proUnlimited": false,
            "stationPermalink": "https://soundcloud.com/discover/sets/artist-stations:3685019"
          }
        },
        {
          "type": "track",
          "id": 1146061297,
          "permalink": "https://soundcloud.com/edsheeran/ed-sheeran-stop-the-rain",
          "createdAt": "2021-10-22T11:20:28Z",
          "lastModified": "2023-10-25T23:58:33Z",
          "title": "Ed Sheeran - Stop The Rain",
          "caption": null,
          "description": null,
          "goPlus": false,
          "durationMs": 203520,
          "durationText": "03:23",
          "artworkUrl": "https://i1.sndcdn.com/artworks-VUOsKZzUm80A-0-original.jpg",
          "releaseDate": "2021-10-29T00:00:00Z",
          "genre": "Pop",
          "labelName": "Atlantic Records UK",
          "license": "all-rights-reserved",
          "purchaseTitle": null,
          "purchaseUrl": null,
          "commentable": true,
          "commentCount": 38,
          "likeCount": 1281,
          "playCount": 89108,
          "repostCount": 114,
          "waveformUrl": "https://wave.sndcdn.com/nozeN5aS7l40_m.json",
          "stationPermalink": "https://soundcloud.com/discover/sets/track-stations:1146061297",
          "visuals": [],
          "publisher": {
            "albumTitle": "=",
            "artist": "Ed Sheeran",
            "writerComposer": "Ed Sheeran",
            "upcOrEan": "190296491412",
            "isrc": "GBAHS2100678",
            "pLine": "℗ An Asylum Records UK release, a division of Atlantic Records UK, ℗ 2021 Warner Music UK Limited",
            "cLine": "© An Asylum Records UK release, a division of Atlantic Records UK, © 2021 Warner Music UK Limited"
          },
          "tags": [],
          "user": {
            "type": "user",
            "id": 3685019,
            "permalink": "https://soundcloud.com/edsheeran",
            "lastModified": "2023-09-29T05:02:30Z",
            "name": "Ed Sheeran",
            "avatarUrl": "https://i1.sndcdn.com/avatars-p1k8SAWgqCaOVZMa-8Z8LOQ-original.jpg",
            "followerCount": 2470753,
            "city": "",
            "countryCode": null,
            "verified": true,
            "pro": false,
            "proUnlimited": false,
            "stationPermalink": "https://soundcloud.com/discover/sets/artist-stations:3685019"
          }
        }
      ]
    
  